-- MySQL Script generated by MySQL Workbench
-- jue 23 feb 2017 02:50:37 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CEUPNA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CEUPNA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CEUPNA` DEFAULT CHARACTER SET utf8 ;
USE `CEUPNA` ;

-- -----------------------------------------------------
-- Table `CEUPNA`.`Studies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`Studies` (
  `idStudies` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idStudies`))
ENGINE = InnoDB
COMMENT = 'Devuelve todos los estudios posibles de grado y master';


-- -----------------------------------------------------
-- Table `CEUPNA`.`Studies-Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`Studies-Subject` (
  `idStudies-Subject` INT NOT NULL AUTO_INCREMENT,
  `idStudies` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idStudies-Subject`),
  INDEX `fk_Studies-Subject_idx` (`idStudies` ASC),
  CONSTRAINT `fk_Studies-Subject`
    FOREIGN KEY (`idStudies`)
    REFERENCES `CEUPNA`.`Studies` (`idStudies`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Devuelve las asignaturas de cada estudio';


-- -----------------------------------------------------
-- Table `CEUPNA`.`Studies-Subject-Id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`Studies-Subject-Id` (
  `idStudies-Subject-Id` INT NOT NULL AUTO_INCREMENT,
  `Studies-Subject` INT NULL,
  `guide` VARCHAR(255) NOT NULL COMMENT 'link a la guia de la asignatura',
  `semester` TINYINT(1) NOT NULL COMMENT 'Semestre 1 o 2',
  PRIMARY KEY (`idStudies-Subject-Id`),
  INDEX `fk_Studies-Subject-Id_1_idx` (`Studies-Subject` ASC),
  CONSTRAINT `fk_Studies-Subject-Id_1`
    FOREIGN KEY (`Studies-Subject`)
    REFERENCES `CEUPNA`.`Studies-Subject` (`idStudies-Subject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEUPNA`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`Schedule` (
  `idschedule` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `date-begin` DATETIME NOT NULL,
  `date-end` DATETIME NULL,
  `description` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`idschedule`))
ENGINE = InnoDB
COMMENT = 'Tabla de la agenda';


-- -----------------------------------------------------
-- Table `CEUPNA`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`Teachers` (
  `idteachers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`idteachers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEUPNA`.`TeachersById`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`TeachersById` (
  `idteachersById` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` INT(9) NULL,
  `department` VARCHAR(150) NULL,
  `timetable` VARCHAR(255) NULL COMMENT 'Horario de tutorias',
  `teachers-id-fk` INT NULL,
  PRIMARY KEY (`idteachersById`),
  INDEX `fk_teachersById_1_idx` (`teachers-id-fk` ASC),
  CONSTRAINT `fk_teachersById_1`
    FOREIGN KEY (`teachers-id-fk`)
    REFERENCES `CEUPNA`.`Teachers` (`idteachers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Informacion de cada profesor';


-- -----------------------------------------------------
-- Table `CEUPNA`.`TeachersBySubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`TeachersBySubject` (
  `idteachersBySubject` INT NOT NULL AUTO_INCREMENT,
  `idTeacher` INT NULL,
  `idSubject` INT NULL,
  PRIMARY KEY (`idteachersBySubject`),
  INDEX `fk_teachersBySubject_teacherId_idx` (`idTeacher` ASC),
  INDEX `fk_teachersBySubject_subjectId_idx` (`idSubject` ASC),
  CONSTRAINT `fk_teachersBySubject_teacherId`
    FOREIGN KEY (`idTeacher`)
    REFERENCES `CEUPNA`.`Teachers` (`idteachers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teachersBySubject_subjectId`
    FOREIGN KEY (`idSubject`)
    REFERENCES `CEUPNA`.`Studies-Subject` (`idStudies-Subject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Tabla que relaciona los profesores con las asignaturas\n';


-- -----------------------------------------------------
-- Table `CEUPNA`.`Alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`Alerts` (
  `idAlerts` INT NOT NULL,
  `title` VARCHAR(55) NULL,
  `date-begin` DATETIME NULL COMMENT '\'YYYY-MM-DD HH:MM:SS\'',
  `date-end` DATETIME NULL COMMENT '\'YYYY-MM-DD HH:MM:SS\'\n',
  `description` VARCHAR(45) NULL,
  `relevance` INT NULL,
  `push-notification` TINYINT(1) NULL,
  PRIMARY KEY (`idAlerts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEUPNA`.`AlertsByStudies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`AlertsByStudies` (
  `idAlertsByStudies` INT NOT NULL AUTO_INCREMENT,
  `Alerts` INT NULL,
  `Studies` INT NULL,
  PRIMARY KEY (`idAlertsByStudies`),
  INDEX `fk_AlertsByStudies_alert_idx` (`Alerts` ASC),
  INDEX `fk_AlertsByStudies_study_idx` (`Studies` ASC),
  CONSTRAINT `fk_AlertsByStudies_alert`
    FOREIGN KEY (`Alerts`)
    REFERENCES `CEUPNA`.`Alerts` (`idAlerts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AlertsByStudies_study`
    FOREIGN KEY (`Studies`)
    REFERENCES `CEUPNA`.`Studies-Subject` (`idStudies-Subject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEUPNA`.`TIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`TIC` (
  `idTIC` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(55) NULL,
  `icon` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `link` VARCHAR(255) NULL,
  PRIMARY KEY (`idTIC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEUPNA`.`Notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`Notes` (
  `idNotes` INT NOT NULL AUTO_INCREMENT,
  `degree` INT NULL,
  `semester` TINYINT(1) NULL,
  PRIMARY KEY (`idNotes`),
  INDEX `fk_Notes_degree_idx` (`degree` ASC),
  CONSTRAINT `fk_Notes_degree`
    FOREIGN KEY (`degree`)
    REFERENCES `CEUPNA`.`Studies` (`idStudies`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEUPNA`.`NotesByDegree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEUPNA`.`NotesByDegree` (
  `idNotesByDegree` INT NOT NULL,
  `note` INT NULL,
  `title` VARCHAR(45) NULL,
  `subject` INT NULL,
  `link` VARCHAR(45) NULL,
  PRIMARY KEY (`idNotesByDegree`),
  INDEX `fk_NotesByDegree_subject_idx` (`subject` ASC),
  INDEX `fk_NotesByDegree_note_idx` (`note` ASC),
  CONSTRAINT `fk_NotesByDegree_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `CEUPNA`.`Studies-Subject` (`idStudies-Subject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotesByDegree_note`
    FOREIGN KEY (`note`)
    REFERENCES `CEUPNA`.`Notes` (`idNotes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
