# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0004_tic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('center_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('acronym', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('url', models.URLField(blank=True, default='')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='tic',
            name='link',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tic',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tic',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='timetable',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='tic',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tic',
            name='icon',
            field=models.URLField(blank=True, default=''),
        ),
    ]
