# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0007_auto_20170608_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ('created',), 'verbose_name': 'centro', 'verbose_name_plural': 'centros'},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ('created',), 'verbose_name': 'titulación', 'verbose_name_plural': 'titulaciones'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('created',), 'verbose_name': 'asignatura', 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('created',), 'verbose_name': 'profesor', 'verbose_name_plural': 'profesores'},
        ),
        migrations.AlterModelOptions(
            name='tic',
            options={'ordering': ('created',), 'verbose_name': 'TIC', 'verbose_name_plural': 'TIC'},
        ),
        migrations.RenameField(
            model_name='center',
            old_name='url',
            new_name='web',
        ),
        migrations.RenameField(
            model_name='tic',
            old_name='url',
            new_name='web',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='url',
        ),
        migrations.AddField(
            model_name='degree',
            name='web',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='degree',
            name='center',
        ),
        migrations.AddField(
            model_name='degree',
            name='center',
            field=models.ManyToManyField(to='mobile_app.Center'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='contents',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='curriculum',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='evaluation',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='mobile_app.Teacher'),
        ),
    ]
