# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0009_auto_20170612_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Inglés'), ('eus', 'Euskera'), ('fr', 'Francés')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='degree',
            name='upna_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Inglés'), ('eus', 'Euskera'), ('fr', 'Francés')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('ba', 'Básica'), ('ob', 'Obligatoria'), ('op', 'Optativa')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='upna_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
