# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0010_auto_20170613_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=150, unique=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_es', models.CharField(blank=True, default='', max_length=150)),
                ('name_eus', models.CharField(blank=True, default='', max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('last_version', models.URLField(blank=True)),
                ('rule_group', models.CharField(blank=True, choices=[('ens', 'Enseñanzas'), ('est', 'Estudiantes'), ('gen', 'General')], default='', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ('upna_id',), 'verbose_name': 'titulación', 'verbose_name_plural': 'titulaciones'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='timetable',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mobile_app.Person')),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
            bases=('mobile_app.person',),
        ),
    ]
