# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0013_event_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
