# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0016_auto_20171209_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representative',
            options={'ordering': ('created',), 'verbose_name': 'representante', 'verbose_name_plural': 'representantes'},
        ),
        migrations.AddField(
            model_name='representative',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='miaulario',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='representative',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='photo',
            field=models.ImageField(blank=True, upload_to='representatives'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellidos'),
        ),
    ]
