# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0024_center_number_quality_representative_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_es', models.CharField(blank=True, default='', max_length=150)),
                ('name_eus', models.CharField(blank=True, default='', max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('rule_group', models.CharField(blank=True, choices=[('ens', 'Enseñanzas'), ('est', 'Estudiantes'), ('gen', 'General')], default='', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'normativa',
                'verbose_name_plural': 'normativas',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('document', models.URLField(blank=True, default='')),
                ('date', models.DateField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Rule')),
            ],
            options={
                'verbose_name': 'versión',
                'verbose_name_plural': 'versiones',
                'ordering': ('rule', 'created'),
            },
        ),
        migrations.AddField(
            model_name='representative',
            name='sex',
            field=models.CharField(blank=True, choices=[('h', 'Hombre'), ('m', 'Mujer')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(blank=True, choices=[('h', 'Hombre'), ('m', 'Mujer')], default='', max_length=1),
        ),
    ]
