# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0002_auto_20170416_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='timetable',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
