# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0005_auto_20170420_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tic',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
