# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0008_auto_20170610_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='language',
            field=models.CharField(blank=True, default='', max_length=3, validators=['es', 'en', 'eus', 'fr']),
        ),
        migrations.AlterField(
            model_name='center',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='language',
            field=models.CharField(blank=True, default='', max_length=3, validators=['es', 'en', 'eus', 'fr']),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, default='', max_length=2, validators=['ba', 'ob', 'op']),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tic',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together=set([('upna_id', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('upna_id', 'language')]),
        ),
    ]
