# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0011_auto_20170924_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('ical_id', models.CharField(blank=True, default='', max_length=100)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('schedule', models.CharField(choices=[('inst', 'Institucional'), ('ceupna', 'Consejo de Estudiantes')], default='', max_length=6)),
                ('tag', models.CharField(blank=True, choices=[('ens', 'Enseñanzas'), ('est', 'Estudiantes'), ('gen', 'General')], default='', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='StudentCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
