# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0015_auto_20171209_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representative',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='representative',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
