# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0017_auto_20171210_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_es', models.CharField(blank=True, default='', max_length=100)),
                ('name_eus', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('web', models.URLField(blank=True, default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ('active', 'name_es'),
            },
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.DeleteModel(
            name='StudentCouncil',
        ),
        migrations.AddField(
            model_name='representative',
            name='claustral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='delegate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='department',
            name='representative_member',
            field=models.ManyToManyField(to='mobile_app.Representative'),
        ),
    ]
