# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0018_auto_20171223_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representative',
            options={'ordering': ('-active', 'last_name', 'first_name'), 'verbose_name': 'representante', 'verbose_name_plural': 'representantes'},
        ),
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Teacher'),
            preserve_default=False,
        ),
    ]
