# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0019_auto_20171225_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('first_name', 'created'), 'verbose_name': 'profesor', 'verbose_name_plural': 'profesores'},
        ),
        migrations.AlterField(
            model_name='department',
            name='director',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Teacher'),
        ),
        migrations.AlterField(
            model_name='department',
            name='representative_member',
            field=models.ManyToManyField(blank=True, to='mobile_app.Representative'),
        ),
    ]
