# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0020_auto_20171226_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Degree')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Representative')),
            ],
        ),
        migrations.AddField(
            model_name='representative',
            name='degree',
            field=models.ManyToManyField(through='mobile_app.RepresentativeDegree', to='mobile_app.Degree'),
        ),
    ]
