# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0021_auto_20171228_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterQualityRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CenterRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='representative_member',
        ),
        migrations.AddField(
            model_name='center',
            name='number_representative_members',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='number_representative_members',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='representativedegree',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representativedegree',
            name='init_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='departmentrepresentative',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Department'),
        ),
        migrations.AddField(
            model_name='departmentrepresentative',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Representative'),
        ),
        migrations.AddField(
            model_name='centerrepresentative',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Center'),
        ),
        migrations.AddField(
            model_name='centerrepresentative',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Representative'),
        ),
        migrations.AddField(
            model_name='centerqualityrepresentative',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Center'),
        ),
        migrations.AddField(
            model_name='centerqualityrepresentative',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Representative'),
        ),
        migrations.AddField(
            model_name='center',
            name='quality_representative_members',
            field=models.ManyToManyField(related_name='quality_representatives', through='mobile_app.CenterQualityRepresentative', to='mobile_app.Representative'),
        ),
        migrations.AddField(
            model_name='center',
            name='representative_members',
            field=models.ManyToManyField(related_name='representatives', through='mobile_app.CenterRepresentative', to='mobile_app.Representative'),
        ),
        migrations.AddField(
            model_name='department',
            name='representative_members',
            field=models.ManyToManyField(through='mobile_app.DepartmentRepresentative', to='mobile_app.Representative'),
        ),
    ]
