# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0023_auto_20180110_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='number_quality_representative_members',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
