# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0025_auto_20180113_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_es', models.CharField(blank=True, default='', max_length=100)),
                ('name_eus', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibilityRepresentativeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Representative')),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Responsibility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_es', models.CharField(blank=True, default='', max_length=100)),
                ('name_eus', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('web', models.URLField(blank=True, default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Center')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='responsibility',
            name='representative',
            field=models.ManyToManyField(related_name='responsibility_representatives', through='mobile_app.ResponsibilityRepresentativeHistory', to='mobile_app.Representative'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='student_council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.StudentCouncil'),
        ),
    ]
