# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0026_auto_20180114_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentcouncil',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Center'),
        ),
    ]
